language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true


services:
  - docker

before-script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"

